# yaml-language-server: $schema=https://json.schemastore.org/traefik-v3.json
log:
  level: INFO

accessLog: {}

api:
  dashboard: true
  insecure: true

ping: {} # used by the container healthcheck

entryPoints:
  web:
    address: ":80"

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true

experimental:
  localPlugins:
    traedis:
      moduleName: github.com/branchard/traedis
