# yaml-language-server: $schema=https://json.schemastore.org/traefik-v3.json
log:
  level: INFO

accessLog: {}

tracing:
  otlp:
    grpc:
      endpoint: "tracer:4317"

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true

experimental:
  localPlugins:
    traedis:
      moduleName: github.com/branchard/traedis
