displayName: Traedis
type: middleware
iconPath: assets/icon.png
import: github.com/branchard/traedis/pkg
basePkg: traedis
summary: 'Redis-backed HTTP cache for Traefik'
testData:
  redis:
    dsn: "redis://localhost:6379/0"
    timeout: 50ms
  statusCodes: [ 200 ]
  defaultTtl: 5m
  staleTtl: 1h
  defaultStaleWhileRevalidate: 0s
  defaultStaleIfError: 0s
  maxBodyBytes: 5242880
  maxVariants: 16
  sortQuery: false
  exposeKey: false
