services:
  ingress:
    image: traefik:v3.7
    ports:
      - "8080:8080"
    develop:
      watch:
        - path: ./example/traefik.yml
          target: /etc/traefik/traefik.yml
          action: sync+restart
        - path: ./example/placeholder.yml
          target: /etc/traefik/dynamic/placeholder.yml
          action: sync
        - path: ./example/cache.yml
          target: /etc/traefik/dynamic/cache.yml
          action: sync

  cache:
    image: redis:8-alpine
    volumes:
      - http-cache:/data
    environment:
      - REDIS_ARGS=--maxmemory 512mb --maxmemory-policy allkeys-lru

  placeholder:
    image: ghcr.io/branchard/open-placeholder:latest

volumes:
  http-cache:
