services:
  ingress:
    image: traefik:v3.7
    ports:
      - "8080:80"
      - "8081:8080"
    volumes:
      - ./example/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./example/dynamic:/etc/traefik/dynamic:ro

  cache:
    image: redis:8-alpine
    volumes:
      - http-cache:/data
    environment:
      - REDIS_ARGS=--maxmemory 512mb --maxmemory-policy allkeys-lru

  placeholder:
    image: ghcr.io/branchard/open-placeholder:latest

volumes:
  http-cache:
